references: fasta/references.fasta
simulations: 100000
targets:
  IGHV1-2-02:
    fasta:
      - fasta/IGHV1-2-02.fasta
  IGHV1-69-01:
    fasta:
      - fasta/IGHV1-69-01.fasta
  IGHV3-21-01:
    fasta:
      - fasta/IGHV3-21-01.fasta
  IGKV3:
    fasta:
      - fasta/IGKV3-11-01.fasta
      - fasta/IGKV3-15-01.fasta
      - fasta/IGKV3-20-01.fasta
  IGLV2:
    fasta:
      - fasta/IGLV2-23-01.fasta
      - fasta/IGLV2-14-01.fasta
      - fasta/IGLV2-23-02.fasta
groups:
  IGV:
    - IGHV1-2-02
    - IGHV1-69-01
    - IGHV3-21-01
    - IGKV3
    - IGLV2
