name: tandem-simulation
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.6
  - numpy>=1.16.0
  - pandas>=0.24.1
  - scipy>=1.3.0
  - matplotlib>=3.0.0
  - seaborn>=0.9.0
  - snakemake>=5.5.0
