name: tandem-simulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - biopython=1.77
  - numpy=1.18.5
  - pandas=1.0.5
  - pyyaml=5.3.1
  - scipy=1.5.0
  - matplotlib=3.2.2
  - seaborn=0.10.1
