BootStrap: library
From: debian:10

%labels
    Author Diego Alvarez S. (dialvarezs@gmail.com)
    MyLabel tandem-simulation
    Description to use with https://github.com/CATG-UMAG/tandem-substitution-simulation

%post
    apt update && apt upgrade -y
    apt install -y python3 python3-pip wget
    wget https://raw.githubusercontent.com/CATG-UMAG/tandem-substitution-simulation/master/env/requirements.txt
    pip3 install -r requirements.txt
