BootStrap: docker
From: python:3.8-slim-buster

%labels
    Author Diego Alvarez S. (dialvarezs@gmail.com)
    MyLabel tandem-simulation
    Description to use with https://github.com/CATG-UMAG/tandem-substitution-simulation

%post
    apt update && apt upgrade -y
    pip3 install -r https://raw.githubusercontent.com/CATG-UMAG/tandem-substitution-simulation/master/env/requirements.txt
